export default {
  ITEM_TYPE_NORMAL: 1,
  ITEM_TYPE_GIFT: 2,
  GOODS_STATUS_FOR_SALE: 2,
  GOODS_STATUS_NOT_FOR_SALE: 3,
  GOODS_STATUS_ONLY_DISPLAY: 5,
  PROMOTION_FULLCUT_RULE_TYPE_DISCOUNT: 1,
  PROMOTION_FULLCUT_RULE_TYPE_GIFT: 2,
  PROMOTION_FULLCUT_RULE_TYPE_DISCOUNT_AND_GIFT: 3
}
